/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/articles` | `/articles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/index.test` | `/__tests__/index.test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/lab4.test` | `/__tests__/lab4.test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/mediaScreenIntegration.test` | `/__tests__/mediaScreenIntegration.test`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/articles` | `/articles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/__tests__/index.test` | `/__tests__/index.test`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/__tests__/lab4.test` | `/__tests__/lab4.test`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/__tests__/mediaScreenIntegration.test` | `/__tests__/mediaScreenIntegration.test`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/articles${`?${string}` | `#${string}` | ''}` | `/articles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/auth${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/__tests__/index.test${`?${string}` | `#${string}` | ''}` | `/__tests__/index.test${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/__tests__/lab4.test${`?${string}` | `#${string}` | ''}` | `/__tests__/lab4.test${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/__tests__/mediaScreenIntegration.test${`?${string}` | `#${string}` | ''}` | `/__tests__/mediaScreenIntegration.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/articles` | `/articles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/index.test` | `/__tests__/index.test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/lab4.test` | `/__tests__/lab4.test`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/__tests__/mediaScreenIntegration.test` | `/__tests__/mediaScreenIntegration.test`; params?: Router.UnknownInputParams; };
    }
  }
}
